CREATE TABLE `tb_plan_order` (
  `order_id` bigint(20) NOT NULL COMMENT '订单ID',
  `account_id` bigint(20) NOT NULL COMMENT '交易账户ID',
  `client_order_id` varchar(255) NOT NULL COMMENT '客户端订单ID',
  `broker_id` bigint(20) NOT NULL DEFAULT '0' COMMENT 'broker id',
  `exchange_id` bigint(20) NOT NULL DEFAULT '0' COMMENT 'exchange id',
  `symbol_id` varchar(255) NOT NULL COMMENT '币对名称',
  `trigger_price` decimal(65,18) NOT NULL COMMENT '触发价格',
  `price` decimal(65,18) NOT NULL COMMENT '订单价格',
  `quantity` decimal(65,18) NOT NULL COMMENT '订单数量',
  `side` varchar(255) NOT NULL DEFAULT '' COMMENT '买卖方向，BUY/SELL',
  `is_close` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否是平仓单（0-开仓单，1-平仓单）',
  `contract_direction` tinyint(4) NOT NULL DEFAULT '1' COMMENT '1-正向合约 0-反向合约',
  `leverage` decimal(65,18) NOT NULL DEFAULT '0.000000000000000000' COMMENT '杠杆',
  `status` varchar(255) NOT NULL DEFAULT '' COMMENT '委托单状态: ORDER_NEW-委托建立 ORDER_CANCELED-取消委托 ORDER_FILLED-委托完成',
  `trigger_status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '委托单触发状态：0等待触发 10触发中 20下单成功 30下单拒绝 40下单失败 -1下单错误',
  `trigger_msg` text COMMENT '触发grpc服务响应消息',
  `executed_price` decimal(65,18) DEFAULT '0.000000000000000000' COMMENT '成交价格',
  `executed_quantity` decimal(65,18) DEFAULT '0.000000000000000000' COMMENT '成交数量',
  `executed_order_id` bigint(20) DEFAULT NULL COMMENT '成交订单ID',
  `created_at` timestamp(3) NOT NULL COMMENT '创建时间',
  `updated_at` timestamp(3) NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`order_id`),
  UNIQUE KEY `accountId_orderId_idx` (`account_id`,`order_id`),
  UNIQUE KEY `accountId_clientOrderId` (`account_id`,`client_order_id`),
  KEY `acountId_idx` (`account_id`),
  KEY `updatedAt_idx` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单计划委托表';