CREATE TABLE `tb_plan_spot_order` (
  `order_id` bigint(20) NOT NULL COMMENT '订单ID',
  `account_id` bigint(20) NOT NULL COMMENT '交易账户ID',
  `account_type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '交易账户类型0币币27杠杆',
  `broker_user_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '交易用户id',
  `client_order_id` varchar(255) NOT NULL COMMENT '客户端订单ID',
  `broker_id` bigint(20) NOT NULL DEFAULT '0' COMMENT 'broker id',
  `exchange_id` bigint(20) NOT NULL DEFAULT '0' COMMENT 'exchange id',
  `symbol_id` varchar(255) NOT NULL COMMENT '币对名称',
  `trigger_price` decimal(65,18) NOT NULL COMMENT '触发价格',
  `price` decimal(65,18) NOT NULL COMMENT '订单价格',
  `quantity` decimal(65,18) NOT NULL COMMENT '订单数量',
  `quote_price` decimal(65,18) NOT NULL COMMENT '委托时的行情价格',
  `amount` decimal(65,18) NOT NULL COMMENT '委托额',
  `order_type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '订单状态：如 LIMIT = 0',
  `side` varchar(255) NOT NULL DEFAULT '' COMMENT '买卖方向，BUY/SELL',
  `time_in_force` varchar(255) NOT NULL DEFAULT '' COMMENT '订单持续时间,GTC/FOK/IOC',
  `status` varchar(255) NOT NULL DEFAULT '' COMMENT '委托单状态: ORDER_NEW-委托建立 ORDER_CANCELED-取消委托 ORDER_FILLED-委托完成',
  `trigger_status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '委托单触发状态：0等待触发 10触发中 20下单成功 30下单拒绝 40下单失败 -1下单错误',
  `trigger_msg` text COMMENT '触发grpc服务响应消息',
  `maker_fee_rate` decimal(65,18) DEFAULT '0.000000000000000000' COMMENT '适用MAKER的手续费率',
  `taker_fee_rate` decimal(65,18) DEFAULT '0.000000000000000000' COMMENT '适用TAKER的手续费率',
  `maker_bonus_rate` decimal(65,18) DEFAULT '0.000000000000000000' COMMENT '创世的费率',
  `executed_price` decimal(65,18) DEFAULT '0.000000000000000000' COMMENT '成交价格',
  `executed_quantity` decimal(65,18) DEFAULT '0.000000000000000000' COMMENT '成交数量',
  `executed_order_id` bigint(20) DEFAULT NULL COMMENT '成交订单ID',
  `created_at` timestamp(3) NOT NULL COMMENT '创建时间',
  `updated_at` timestamp(3) NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`order_id`),
  UNIQUE KEY `orgId_accountId_clientOrderId_idx` (`broker_id`,`account_id`,`client_order_id`),
  KEY `orderType_side_idx` (`order_type`,`side`),
  KEY `status_idx` (`status`),
  KEY `createdAt_idx` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='现货订单计划委托表';